In [1]:
import pandas as pd

In [3]:
a = pd.read_csv('../data/processed/ensembl_annotation_trs_uniprot_20220429.csv', low_memory=False)

In [4]:
m = pd.read_excel('../reports/missing_hek_select_20220518.xlsx', index_col=[0,1,2]).reset_index()

In [7]:
a = a.drop_duplicates('ensembl_trs_id')

In [9]:
m2 = pd.DataFrame()

In [12]:
m2 = a[a['ensembl_gene_name'].isin(m['ensembl_gene_name'].unique())]

In [13]:
m2

,ensembl_gene_name,ensembl_gene_id,ensembl_trs_id,ensembl_is_canonical,trs_type,trs_length_bp,ensembl_protein_id,uniprot_base,uniprot_isoform
5288,AGAP9,ENSG00000204172,ENST00000452145,True,protein_coding,2387,ENSP00000392206,Q5VTM2,Q5VTM2-2
21881,C1orf54,ENSG00000118292,ENST00000369102,False,protein_coding,1251,ENSP00000358098,Q8WWF1,Q8WWF1-1
21882,C1orf54,ENSG00000118292,ENST00000369099,True,protein_coding,509,ENSP00000358095,Q8WWF1,Q8WWF1-1
21883,C1orf54,ENSG00000118292,ENST00000369098,False,protein_coding,418,ENSP00000358094,NaN,NaN
36991,CNPY1,ENSG00000146910,ENST00000406197,False,protein_coding,560,ENSP00000384514,Q3B7I2,Q3B7I2-1
...,...,...,...,...,...,...,...,...,...
216480,TSPAN17,ENSG00000048140,ENST00000514705,False,retained_intron,4445,NaN,NaN,NaN
216481,TSPAN17,ENSG00000048140,ENST00000503030,False,nonsense_mediated_decay,909,ENSP00000425975,NaN,NaN
216482,TSPAN17,ENSG00000048140,ENST00000504168,False,protein_coding,884,ENSP00000423957,NaN,NaN
216483,TSPAN17,ENSG00000048140,ENST00000503045,False,protein_coding,1019,ENSP00000425212,NaN,NaN
216484,TSPAN17,ENSG00000048140,ENST00000507471,False,protein_coding,707,ENSP00000423610,NaN,NaN

In [14]:
h = pd.read_csv('../data/processed/va_cellline_expression_20220517.csv', index_col=0)['HEK293T']

In [16]:
m2['hek293t_tpm'] = m2['ensembl_trs_id'].map(h)

C:\Users\Dynev\AppData\Local\Temp\ipykernel_2564\621210709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  m2['hek293t_tpm'] = m2['ensembl_trs_id'].map(h)

In [17]:
m2

,ensembl_gene_name,ensembl_gene_id,ensembl_trs_id,ensembl_is_canonical,trs_type,trs_length_bp,ensembl_protein_id,uniprot_base,uniprot_isoform,hek293t_tpm
5288,AGAP9,ENSG00000204172,ENST00000452145,True,protein_coding,2387,ENSP00000392206,Q5VTM2,Q5VTM2-2,17.906937
21881,C1orf54,ENSG00000118292,ENST00000369102,False,protein_coding,1251,ENSP00000358098,Q8WWF1,Q8WWF1-1,0.369875
21882,C1orf54,ENSG00000118292,ENST00000369099,True,protein_coding,509,ENSP00000358095,Q8WWF1,Q8WWF1-1,9.431817
21883,C1orf54,ENSG00000118292,ENST00000369098,False,protein_coding,418,ENSP00000358094,NaN,NaN,8.450435
36991,CNPY1,ENSG00000146910,ENST00000406197,False,protein_coding,560,ENSP00000384514,Q3B7I2,Q3B7I2-1,19.871630
...,...,...,...,...,...,...,...,...,...,...
216480,TSPAN17,ENSG00000048140,ENST00000514705,False,retained_intron,4445,NaN,NaN,NaN,NaN
216481,TSPAN17,ENSG00000048140,ENST00000503030,False,nonsense_mediated_decay,909,ENSP00000425975,NaN,NaN,NaN
216482,TSPAN17,ENSG00000048140,ENST00000504168,False,protein_coding,884,ENSP00000423957,NaN,NaN,NaN
216483,TSPAN17,ENSG00000048140,ENST00000503045,False,protein_coding,1019,ENSP00000425212,NaN,NaN,1.833010
216484,TSPAN17,ENSG00000048140,ENST00000507471,False,protein_coding,707,ENSP00000423610,NaN,NaN,NaN

In [3]:
y = 10

def do(x):
    print(id(x))
    x.append(y)
    print(id(x))
    return x

In [2]:
do(5)

3168210977136
3168210977456

15

In [4]:
do([1])

3168292803520
3168292803520

[1, 10]

In [5]:
def smth(x: str) -> str:
    return x + 'lol'

In [6]:
smth('a')

'alol'

In [3]:
hek = [pd.read_csv(f'../data/interim/va_hek293t/HEK293T_{i}.sf', sep='\t') for i in range(1,4)]

In [4]:
for i in hek:
    i.loc[:, 'Name'] = i['Name'].map(lambda x: x[:x.index('.')])

In [5]:
hek[0]

                   Name  Length  EffectiveLength  TPM  NumReads
0       ENST00000631435      12           12.000  0.0       0.0
1       ENST00000415118       8            8.000  0.0       0.0
2       ENST00000434970       9            9.000  0.0       0.0
3       ENST00000448914      13           13.000  0.0       0.0
4       ENST00000632684      12           12.000  0.0       0.0
...                 ...     ...              ...  ...       ...
196717  ENST00000444456     913          756.381  0.0       0.0
196718  ENST00000416377     940          783.329  0.0       0.0
196719  ENST00000318104     951          794.314  0.0       0.0
196720  ENST00000606902     342          189.575  0.0       0.0
196721  ENST00000427827     319          167.785  0.0       0.0

[196722 rows x 5 columns]

In [38]:
hekt = pd.DataFrame(index=hek[0]['Name'])

In [33]:
hekt['TPM'] = np.mean([hek[i]['TPM'].to_numpy() for i in range(len(hek))], axis=0)

In [27]:
import numpy as np

In [37]:
hekt.loc['ENST00000519860']

TPM    0.097381
Name: ENST00000519860, dtype: float64

In [6]:
hekt = hek[0].loc[:, ['Name', 'TPM']].rename({'TPM': 'HEK293T-1'}, axis=1)

In [7]:
hekt['HEK293T-2'] = hekt['Name'].map(hek[1].set_index('Name')['TPM'])

In [8]:
hekt['HEK293T-3'] = hekt['Name'].map(hek[2].set_index('Name')['TPM'])

In [9]:
hekt['HEK293T'] = hekt.set_index('Name', drop=True).mean(axis=1).to_numpy()

In [10]:
hekt = hekt.set_index('Name', drop=True)

In [11]:
hekt.index.name = 'ensembl_trs_id'

In [14]:
hekt.to_csv('../data/processed/hek293t_va_20220525.csv')

In [12]:
hekt.loc['ENST00000367167']

HEK293T-1    7.140646
HEK293T-2    8.327508
HEK293T-3    7.777429
HEK293T      7.748528
Name: ENST00000367167, dtype: float64

In [13]:
hekt

                 HEK293T-1  HEK293T-2  HEK293T-3   HEK293T
ensembl_trs_id
ENST00000631435        0.0        0.0   0.000000  0.000000
ENST00000415118        0.0        0.0   0.000000  0.000000
ENST00000434970        0.0        0.0   0.000000  0.000000
ENST00000448914        0.0        0.0   0.000000  0.000000
ENST00000632684        0.0        0.0   0.000000  0.000000
...                    ...        ...        ...       ...
ENST00000444456        0.0        0.0   0.000000  0.000000
ENST00000416377        0.0        0.0   0.051884  0.017295
ENST00000318104        0.0        0.0   0.000000  0.000000
ENST00000606902        0.0        0.0   0.000000  0.000000
ENST00000427827        0.0        0.0   0.000000  0.000000

[196722 rows x 4 columns]